export const ADD_SPACES = "ADD_SPACES";
export const ADD_SPACE = "ADD_SPACE";
export const EDIT_SPACE = "EDIT_SPACE";
export const DELETE_SPACE = "DELETE_SPACE";
export const SELECT_SPACE = "SELECT_SPACE";

export const ADD_NOTES = "ADD_NOTES";
export const ADD_NOTE = "ADD_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";

export const CHANGE_TIMESTAMP = "CHANGE_TIMESTAMP";
export const CHANGE_CURRTIME = "CHANGE_CURRTIME";

export const ADD_SPACES_ASYNC = "ADD_SPACES_ASYNC";
export const ADD_SPACE_ASYNC = "ADD_SPACE_ASYNC";
export const EDIT_SPACE_ASYNC = "EDIT_SPACE_ASYNC";
export const DELETE_SPACE_ASYNC = "DELETE_SPACE_ASYNC";
export const SELECT_SPACE_ASYNC = "SELECT_SPACE_ASYNC";

export const ADD_NOTES_ASYNC = "ADD_NOTES_ASYNC";
export const ADD_NOTE_ASYNC = "ADD_NOTE_ASYNC";
export const EDIT_NOTE_ASYNC = "EDIT_NOTE_ASYNC";
export const DELETE_NOTE_ASYNC = "DELETE_NOTE_ASYNC";
